### ISSUE TITLE
Is that bug?

### ISSUE THREAD

**Issue by zhongyong** [sysstat/sysstat#161] opened 2017-08-23 09:19 UTC
+This file contains the data that you should provide to report a bug:
+
+System info: [Include sysstat version (e.g., the output of "sar -V" or "iostat -V" etc.),
9.0.4
+operating system name (e.g., the output of "uname -a"), and other relevant details]
Linux 2.6.32-431.el6.x86_64
+Steps to reproduce:
+
+    [sar –dp 1 1]
+     %util
     2260.00

    >100%  %util
+Expected behavior: [What you expected to happen]
+
+Actual behavior: [What actually happened]
+
+Additional info: [Include gist of relevant binary system activity datafile, config, logs, etc.
+or send them directly to me at sysstat <at> orange_dot_fr]

**Comment by sysstat** [comment] 2017-08-25 08:52
Sorry, I cannot reproduce the bug. At least send me a binary sa datafile that shows the problem.
Please also try to use a more recent version of sysstat (9.0.4 was released 8 years ago...!)

**Comment by sysstat** [comment] 2018-07-24 13:42
Closing this issue (no news from submitter).

**Closed by sysstat** 2018-07-24 13:42 UTC
